### ISSUE TITLE
Attempt to index field 'preloadheaders' (a nil value)

### ISSUE THREAD

**Issue by ghost** [horzadome/nginx_preloadheaders#6]
Hello,

I've attempted to install this on a CentOS 7 server running Nginx 1.9.9. The server is a reverse proxy. I followed the instructions exactly. The website now shows a 500 page with this in the logs (loglevel warn):

```
2016/07/29 19:33:56 [error] 26009#26009: *20 lua entry thread aborted: runtime error: rewrite_by_lua(domain.com.conf:126):7: attempt to index field 'preloadheaders' (a nil value)
stack traceback:
coroutine 0:
    rewrite_by_lua(domain.com.conf:126):7: in function <rewrite_by_lua(domain.com.conf:126):1>, client: 192.154.111.10, server: www.domain.com, request: "GET / HTTP/1.1", host: "www.domain.com"
```

I've tried updating https://github.com/openresty/lua-nginx-module to the latest version as I assume it depends on that.

I also thought that perhaps the Lua module is not being loaded at all (I assume that's how the field is created (?)). This is the line to load the module in the `http` block:

```
lua_package_path    "/usr/local/nginx/lua-modules/?.lua;;";
```

And the module is in there:

```
[root@server conf]# ls /usr/local/nginx/lua-modules
preloadheaders.lua
```

This module looks like it would be extremely useful for me - and I'm sure I'm missing something. Can you suggest anything?

Thanks!

**Comment by horzadome** [comment]
Ouch. My bad. Haven't updated that part of the readme when I changed the shared dictionary name.
Instead of this:

```
lua_package_path    "/etc/nginx/lua-modules/?.lua;;";
lua_shared_dict     log_dict    1M;
```

Make it this:

```
lua_package_path    "/etc/nginx/lua-modules/?.lua;;";
lua_shared_dict     preloadheaders    1M;
```

I've updated the readme now; commit d6d6cbe . 
Sorry for the error and thank you for reporting it!
